### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by PositionWizard** [MuruCoder/TR123R-Blender-Addon#1]
Hey, I'm Czarpos from the TR Forums and would like to fork this repo but it has no license. Could you include a LICENSE file and specify on what terms can this be shared with others?
Here's GitHub's guidelines on this topic: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by MuruCoder** [comment]
OK, picked one. Not sure if it's the best fit but sounds good enough.

**Comment by PositionWizard** [comment]
Yea, I guess that's fine, thanks!
